services:
  # Service pour l'application Node.js (Express)
  ms-auth:
    image: node:20-alpine
    container_name: ms-auth
    working_dir: /app
    ports:
      - "3000:3000"  # Expose le port 3000 sur l'hôte
    volumes:
      - .:/app
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - ms-network
    command: ["npm", "start"]  # Commande pour démarrer votre application

  # Service pour la base de données PostgreSQL
  db:
    image: postgres:17-alpine
    container_name: ms-auth-db
    networks:
      - ms-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"  # Expose le port 5432 pour PostgreSQL

networks:
  ms-network:
    external: true
